// useActivateQuery
// useActivateMutation
// useEnsureInitializedQuery
// useEnsureInitializedMutation
// useFetchAndActivateQuery
// useFetchAndActivateMutation
// useFetchConfigQuery
// useFetchConfigMutation
// useGetAllQuery