// useDeleteObjectMutation
// useGetBlobQuery
// useGetBytesQuery
// useGetDownloadURLQuery
// useGetMetadataQuery
// useListQuery
// useListAllQuery
// useUpdateMetadataMutation
// useUploadBytesMutation